### ISSUE TITLE
Build keretrendszer beüzemelése, ha még nincs (Maven, Gradle...)

### ISSUE THREAD

**Issue by vandreas73** [BME-MIT-IET/iet-hf-2023-csigi#1]

**Comment by SzelleCsaba** [comment]
I successfully set up Maven with IntelliJ. @vandreas73 You can now use it in your part.

**Comment by SzelleCsaba** [comment]
Please note: The project has a specified version from now on: JDK 17

**Comment by SzelleCsaba** [comment]
Project repository changed: Files structured

**Comment by SzelleCsaba** [comment]
Dependency added to pom: forms_rt

**Comment by SzelleCsaba** [comment]
Problem found: when navigating, to a new form, the application will throw an exception.

I tought the main reason behind it was the compilation of the UI Designer: Binary generation changed to Java source code.
![image](https://github.com/BME-MIT-IET/iet-hf-2023-csigi/assets/100311553/1e793b48-fe1e-4cac-aea3-8385ea2f0070)

**Comment by SzelleCsaba** [comment]
the error:
![image](https://github.com/BME-MIT-IET/iet-hf-2023-csigi/assets/100311553/2bea0d0f-8213-469a-8fb1-f7a67e3603bb)

**Comment by SzelleCsaba** [comment]
Error fixed: i linked the jar externally for the first time, but now it is linked directly in the project.
