### ISSUE TITLE
CI beüzemelése, ha még nincs (Actions, Travis, AppVeyor, Azure Pipelines...)

### ISSUE THREAD

**Issue by vandreas73** [BME-MIT-IET/iet-hf-2023-csigi#2]

**Comment by schauermannb** [comment]
I'm choosed GitHub Actions. It's now working. If any question or problem come up in the future with this, look for me.

**Comment by schauermannb** [comment]
I write an overview from the result here: [Readme overview](https://github.com/BME-MIT-IET/iet-hf-2023-csigi/blob/fa31fa1a41b5e7ef426fb9f5d6abac50ca35fab2/doc/Ci.md)
