### ISSUE TITLE
Manuális tesztek megtervezése, végrehajtása és dokumentálása

### ISSUE THREAD

**Issue by SzelleCsaba** [BME-MIT-IET/iet-hf-2023-csigi#8]

**Comment by SzelleCsaba** [comment]
Test should be documented in this sample: 
[test_sample.xlsx](https://github.com/BME-MIT-IET/iet-hf-2023-csigi/files/11534747/test_sample.xlsx)

**Comment by SzelleCsaba** [comment]
10 use-cases planned, tested, and documented:
[test_SzelleCsaba.xlsx](https://github.com/BME-MIT-IET/iet-hf-2023-csigi/files/11537039/test_SzelleCsaba.xlsx)

**Comment by schauermannb** [comment]
Another 10 use-case witch tested.

**Comment by schauermannb** [comment]
This file contains the documentation of the all manual test:
[manual_tests.xlsx](https://github.com/BME-MIT-IET/iet-hf-2023-csigi/files/11585478/manual_tests.xlsx)

**Comment by schauermannb** [comment]
The documentation is available [here](https://github.com/BME-MIT-IET/iet-hf-2023-csigi/blob/ff67a63172ffa32cf7da7f97ec50867254aac58b/doc/Manual_tests.md)
